config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :users, only: %i[show]
  resources :invoices, only: %i[index show new create edit update] do
    collection do
      get :archives
    end
  end

  post "incoming_invoice", to: "invoices#incoming_invoice"
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  before_validation :set_progress, on: :create
  attr_reader :siren

  PROGRESS = ["À traiter", "Avant échéance", "Phase amiable", "Juridique", "Payé"]
  belongs_to :relationship
  has_one :user, through: :relationship
  has_one :debtor, through: :relationship
  has_many :reminders

  validates :number, :amount, :emission_date, :due_date, presence: true
  validates :progress, inclusion: { in: PROGRESS }
  has_one_attached :file
  # validates :number, uniqueness: true

  def set_progress
    if self.progress.nil?
      self.progress = "À traiter"
    end
  end

  def calculate_average_days_late
    # total_days = 0
    # valid_invoices_count = 0
    unless self.payment_date.nil?
      days_until_paid = (self.payment_date - self.due_date)
      # if days_until_paid.positive?
      #   total_days += days_until_paid
      #   valid_invoices_count += 1
      end
    # end
    # average_days = valid_invoices_count.positive? ? total_days.to_f / valid_invoices_count : 0
    # self.relationship.payment_days = average_days
    # self.relationship.save
    # self.relationship.calculate_average_rating(average_days)
  end

  def self.total_sum_archive
    Invoice.where("payment_date >= '#{Date.today - Date.today.day + 1}'").map(&:amount).sum
  end

  def self.total_sum_before_due_date
    @a = Invoice.where("due_date >= '#{Date.today - Date.today.day + 1}'").where(progress: "Avant échéance").map(&:amount).sum
  end

  def self.total_sum_friendly_phase
    @b = Invoice.where(progress: "Phase amiable").map(&:amount).sum
  end

  def self.total_sum_legal_phase
    @c = Invoice.where(progress: "Juridique").map(&:amount).sum
  end

  def self.sum_collect_by_month
    @a = Invoice.where("due_date >= '#{Date.today - Date.today.day + 1}'").where(progress: "Avant échéance").map(&:amount).sum
    @b = Invoice.where(progress: "Phase amiable").map(&:amount).sum
    @c = Invoice.where(progress: "Juridique").map(&:amount).sum
    @total = [@a, @b, @c].sum
  end
end

app/controllers/invoices_controller.rb
require 'mindee'
require 'open-uri'

class InvoicesController < ApplicationController
  # before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:incoming_invoice]
  skip_before_action :authenticate_user!, only: [:incoming_invoice]

  def index
    @invoices = current_user.invoices.order(created_at: :desc)
    # if params[:query].present?
    #   sql_subquery_number = "number ILIKE :query"
    #   sql_subquery_company = "debtors.company_name ILIKE :query"
    #   search_column = params[:search_by] == 'number' ? sql_subquery_number : sql_subquery_company
    #   @invoices = @invoices.joins(relationship: :debtor).where(search_column, query: "%#{params[:query]}%")
    # end
    if params[:query].present?
      search_query = "%#{params[:query]}%"
      @invoices = @invoices.joins(relationship: :debtor).where("number ILIKE :query OR debtors.company_name ILIKE :query", query: search_query)
    end
  end

  def show
    @show_invoice = true
    @invoice = Invoice.find(params[:id])
    @invoice.reminders.order(action_date: :desc)
  end

  def new
    @user = current_user
    @invoice = Invoice.new
    @debtor = Debtor.new
    @relationship = Relationship.new
    @mindee = MindeeExtractor.new
    @mindee_url = MindeeExtractorUrl.new
  end

  def create
    @mindee = MindeeExtractor.new(params[:invoice][:file].tempfile.path)
    @mindee.perform
    extractor_hash = @mindee.extractor_hash

    @debtor = Debtor.find_by(company_name: extractor_hash[:company_name])
    @debtor ||= Debtor.create(company_name: extractor_hash[:company_name])
    @relationship = Relationship.find_or_initialize_by(debtor: @debtor, user: current_user)
    @relationship.save

    @invoice = Invoice.new(
      number: extractor_hash[:number],
      amount: extractor_hash[:amount],
      emission_date: extractor_hash[:emission_date],
      due_date: extractor_hash[:due_date],
      progress: "À traiter"
    )

    @invoice.file = invoice_params[:file]
    @invoice.relationship = @relationship

    if @invoice.save
      redirect_to invoices_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @invoice = Invoice.find(params[:id])
    @invoice.update(invoice_params)
    @invoice.progress = "Payé" if @invoice.payment_date?
    if @invoice.save
      flash[:notice] = "La facture a bien été modifiée en payée"
      redirect_to archives_invoices_path
    else
      render :edit, status: :unprocessable_entity
    end
    @invoice.relationship.calculate_payment_days
  end

  def archives
    @invoices = current_user.invoices.order(emission_date: :desc)
    @invoices_paid = @invoices.where(progress: "Payé")
    @invoices_paid.each do |invoice|
      invoice.calculate_average_days_late
    end
  end

  def incoming_invoice
    puts "---------"
    puts params
    puts "---------"
    @user = User.find_by(email: params[:sender])

    pdf_url = params[:invoice]
    @mindee_url = MindeeExtractorUrl.new(pdf_url)
    @mindee_url.perform
    extractor_hash = @mindee_url.extractor_hash

    @debtor = Debtor.find_by(company_name: extractor_hash[:company_name])
    @debtor ||= Debtor.create(company_name: extractor_hash[:company_name])
    @relationship = Relationship.find_or_initialize_by(debtor: @debtor, user: @user)
    @relationship.save

    @invoice = Invoice.new(
      number: extractor_hash[:number],
      amount: extractor_hash[:amount],
      emission_date: extractor_hash[:emission_date],
      due_date: extractor_hash[:due_date],
      progress: "À traiter"
    )
    @invoice.relationship = @relationship

    if @invoice.save
      puts "all is good"
      UserChannel.broadcast_to(
        @invoice.user,
        render_to_string(partial: "shared/notification")
      )
      redirect_to invoices_path
    else
      puts @invoice.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  private

  def invoice_params
    params.require(:invoice).permit(:number, :amount, :emission_date, :siren, :due_date, :comment, :progress, :relationship_id, :file, :payment_date)
  end
end

app/views/invoices/_form.html.erb
<div class="container my-4">
    <div class="row justify-content-center">
        <div class="forms-edit col-md-6">
          <%= simple_form_for [@user, @invoice], html: { class: 'custom-form' } do |f| %>
          <h2 class="text-center mb-4 title">Ici tu peux modifier ta facture</h2>
            <div class="d-flex justify-content-evenly">
              <h5>Débiteur : <%= @invoice.debtor.company_name %></h5>
            </div>
            <div class="mt-4">
                  <%= f.input :number, label: 'Numéro de la facture' %>
                  <%= f.input :amount, label: 'Montant de la facture'%>
                  <%= f.input :emission_date, as: :string, label: "Date d'émission de la facture",
                              input_html: { value: @invoice.emission_date.strftime("%d/%m/%y"), data: { controller: "datepicker" } }%>
                  <%= f.input :due_date, as: :string, label: "Date d'échéance de la facture",
                              input_html: { value: @invoice.due_date.strftime("%d/%m/%y"), data: { controller: "datepicker" } }%>
                  <%= f.input :comment, label: "Commentaires"%>
                  <%= f.input :payment_date, as: :string, label: "Date de paiement de la facture",
                              input_html: { data: { controller: "datepicker" } }%>
                <div class="d-flex justify-content-evenly">
                  <%= f.submit "Valide ta modification", class: "btn btn-blue btn-square btn-medium mt-3 align" %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/invoices/_form_edit.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="forms-edit col-md-6">
          <%= simple_form_for [@user, @invoice], html: { class: 'custom-form' } do |f| %>
          <h2 class="text-center title">Ici tu peux modifier ta facture</h2>
            <div class="d-flex justify-content-evenly">
              <h5>Débiteur : <%= @invoice.debtor.company_name %></h5>
            </div>
            <div class="">
                  <%= f.input :number, label: 'Numéro de la facture' %>
                  <%= f.input :amount, label: 'Montant de la facture'%>
                  <%= f.input :emission_date, as: :string, label: "Date d'émission de la facture",
                              input_html: { value: @invoice.emission_date.strftime("%d/%m/%y"), data: { controller: "datepicker" } }%>
                  <%= f.input :due_date, as: :string, label: "Date d'échéance de la facture",
                              input_html: { value: @invoice.due_date.strftime("%d/%m/%y"), data: { controller: "datepicker" } }%>
                  <%= f.input :comment, label: "Commentaires"%>
                  <%= f.input :payment_date, as: :string, label: "Date de paiement de la facture",
                              input_html: { data: { controller: "datepicker" } }%>
                <div class="d-flex justify-content-evenly">
                  <%= f.submit "Valide ta modification", class: "btn btn-blue btn-square btn-medium mt-3 align" %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/invoices/_form_new.html.erb
<div class="container my-4" data-controller="loading">
  <div class="row justify-content-center">
    <div class="forms">
      <%= simple_form_for [invoice], html: { class: 'custom-form' }, multipart: true do |f| %>
        <h1 class="text-start mb-4 ">Déposez une facture</h1>
          <%= f.input :file, as: :file, label: "Déposer ma pièce jointe" %>
        <div id="pdf-info" style="display: ">
          <%= f.input :comment, label: "Commentaires"%>
        </div>
        <div class="d-flex justify-content-end">
        <%= f.submit "Dépose ta facture", class: "btnn btn-square btn-medium  btn-purple my-3 ", data: { action: "click->loading#loadmodal" } %>

        </div>
      <% end %>

    </div>
  </div>
</div>
<%# <div class="modal" id="modal-loading" data-backdrop="static">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-body text-center">
        <div class="loading-spinner mb-2"></div>
        <div>En cours de lecture par les robots de l'agence Surviv.Ai</div>
      </div>
    </div>
  </div>
</div> %>
<!-- Modal -->

app/views/invoices/archives.html.erb
<div class="body-show" >
  <div class="container">
    <h1 class="my-4">Liste des factures archivées</h1>
    <div class="center">
    <div class="col-sm-12 my-3">
      <div class="search-bar-archives my-2 ">
          <%= form_with url: invoices_path, method: :get, class: "d-flex bg-white" do %>
            <%= text_field_tag :query,
                  params[:query],
                  class: "form-control",
                  placeholder: "Filtre par numéro de facture ou par nom d'entreprise"
              %>
            <%= submit_tag "Filtrer", name: "", class: "btnn btn-square-filter btn-blue ml-2" %>
          <% end %>


        </div>

      <div class="cards my-3" >
          <% @invoices_paid.each do |invoice|%>
            <div class="card-invoice card-white">
              <div class="top-card">
                <h4 class="text-blue-light"><strong><%= invoice.debtor.company_name %> </strong> </h4>
                <p class="num-invoice"><strong>Numéro de facture :</strong> <%= invoice.number %> </p>
              </div>
                  <div class="border-blue-light">
                  </div>

              <div class="middle-card">
                <%# <div class="d-flex justify-content-between w-100">
                    <p><strong>Note calculée par Surviv.Ai :</strong></p>
                    <%= render "shared/ratings", rating: invoice.relationship.rating %>
                <%# </div> %>
                <div class="retard">
                  <div class="d-flex justify-content-between w-100">
                      <p>
                      <strong>Jours de retard <br> </strong>                        <% unless invoice.payment_date.nil? %>
                      <% days_until_paid = (invoice.payment_date - invoice.due_date)%>
                      <%= days_until_paid.to_i %>
                      <% end %>
                      </p>
                  </div>
                  <div class="d-flex justify-content-between  text-center align-items-center w-100">
                      <p><strong>Date de paiement </strong> <%= invoice.payment_date&.strftime("%d/%m/%y") %></p>
                  </div>
                </div>

                <div class="d-flex justify-content-center w-100 text-center">
                  <p class="encour-size text-center"><i class="fa-solid fa-coins fa-lg" style="color: #071425;"></i>  <%= number_with_precision(invoice.amount, precision: 2, separator: ',', delimiter: ' ') %> €</p>
                </div>
                  <%= link_to "Voir plus", invoice_path(invoice), class: "btnn btn-round btn-blue btn-small btn-card" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      </div>
  </div>
</div>

app/views/invoices/edit.html.erb
<div class="container my-4">
  <div class="row justify-content-center">
    <div class="forms col-md-6">
      <%= simple_form_for [@user, @invoice], html: { class: 'custom-form' } do |f| %>
        <h2 class="text-center mb-4 title">Ici tu peux modifier ta facture</h2>
       <div class="d-flex justify-content-evenly">
        <h5>Débiteur : <%= @invoice.debtor.company_name %></h5>
       </div>
        <div class="mt-4">
            <%= f.input :number, label: 'Numéro de la facture' %>
            <%= f.input :amount, label: 'Montant de la facture'%>
            <%= f.input :emission_date,
                        as: :string,
                        label: "Date d'émission de la facture",
                        input_html: { data: { controller: "datepicker" } }%>
            <%= f.input :due_date,
                        as: :string,
                        label: "Date d'échéance de la facture",
                        input_html: { data: { controller: "datepicker" } }%>
            <%= f.input :comment, label: "Commentaires"%>
          <div class="d-flex justify-content-evenly">
            <%= f.submit "Valide ta modification", class: "btn btn-blue  btn-medium mt-3 align" %>
          </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/invoices/index.html.erb
<div data-controller="toggle">
  <div class="body-show">
    <div class="container">
      <h1 class="my-4">Liste des factures</h1>
          <div class="row justify-content-start  " data-controller="progress-search">
            <div class="col-sm-1 marge-filter d-flex-column">
          <div class="view-choice row">
            <div class="col-6 clicked center" data-toggle-target="toggableCl">
              <button><i class="fa-solid fa-table-cells-large fa-xl" style="color: #071425;" data-action="click->toggle#fire" ></i></button>
            </div>
            <div class="col-6 center"  data-toggle-target="toggableClass">
              <button><i class="fa-solid fa-list fa-xl" style="color: #071425;" class="" data-action="click->toggle#fire" ></i></button>
            </div>
          </div>
              <div class="sticky-filter">
                <P><STROng>Filtrer par</STROng></P>
                  <button class="btnn-index my-2 border-bottom"
                          style="width: 200"
                          data-action="click->progress-search#searchTraiter"
                          data-progress-search-target="button"
                          data-status="a-traiter">
                          <i class="fa-solid fa-check d-none" data-progress-search-target="icon"></i>
                          A traiter</button>
                  <button class="btnn-index my-2 border-bottom"
                          style="width: 200"
                          data-action="click->progress-search#searchEcheance"
                          data-progress-search-target="button"
                          data-status="avant-echeance">
                          <i class="fa-solid fa-check d-none" data-progress-search-target="icon"></i>
                          Avant échéance</button>
                  <button class="btnn-index my-2 border-bottom"
                          style="width: 200"
                          data-action="click->progress-search#searchAmiable"
                          data-progress-search-target="button"
                          data-status="phase-amiable">
                          <i class="fa-solid fa-check d-none" data-progress-search-target="icon"></i>
                          Phase amiable</button>
                  <button class="btnn-index my-2 border-bottom"
                          style="width: 200"
                          data-action="click->progress-search#searchJuridique"
                          data-progress-search-target="button"
                          data-status="juridique">
                          <i class="fa-solid fa-check d-none" data-progress-search-target="icon"></i>
                          Juridique</button>
              </div>
            </div>
            <div class="col-sm-11 my-3">
                  <div class="search-bar my-2">
                      <%= form_with url: invoices_path, method: :get, class: "d-flex bg-white" do %>
                        <%= text_field_tag :query,
                              params[:query],
                              class: "form-control",
                              placeholder: "Filtre par numéro de facture ou par nom d'entreprise"
                          %>
                        <%= submit_tag "Filtrer", name: "", class: "btnn btn-square-filter btn-blue ml-2" %>
                      <% end %>
                  </div>


            <div class="cards my-3" data-toggle-target="togglableElem" >
              <% @invoices.each do |invoice|%>
                <% if invoice.progress != "Payé" %>
                  <div class="card card-white"
                  data-progress-search-target="card"
                  data-status="<%= invoice.progress.parameterize %>">
                    <div class="top-card d-flex row justify-content-center" style="width:100%">
                      <div class="d-flex justify-content-around col-10">
                        <h4 class="text-blue-light align-items-center"><strong><%= invoice.debtor.company_name %> </strong> </h4>
                        <div class="col-1 shadow-icon icon-manual bg-color-<%= invoice.progress === "À traiter"? 'black' :
                                    invoice.progress === "Avant échéance"? 'blue' :
                                    invoice.progress === "Phase amiable"? 'yellow' :
                                    invoice.progress === "Juridique"? 'red' : ''
                                %>">
                          <div class="icon-manual col-1">
                          </div>
                        </div>
                      </div>
                            <p class=" w-100 num-invoice"><strong>Numéro de facture :</strong> <%= invoice.number %></p>
                  <div class="border-blue-light">
                  </div>
                </div>



                      <div class="middle-card">
                        <div class="date">
                          <div class="d-flex justify-content-between text-center align-items-center w-100">
                              <p><strong>Date d'émission</strong> <%= invoice.emission_date.strftime("%d/%m/%y") %></p>
                          </div>
                          <div class="d-flex justify-content-between text-center align-items-center w-100">
                              <p><strong>Date d'échéance</strong> <%= invoice.due_date.strftime("%d/%m/%y") %></p>
                          </div>
                        </div>
                        <div class="d-flex justify-content-center w-100 text-center">
                            <p class="encour-size text-center"><i class="fa-solid fa-coins fa-lg" style="color: #071425; "></i>  <%= number_with_precision(invoice.amount, precision: 2, separator: ',') %> €</p>
                        </div>
                          <%= link_to "Voir plus", invoice_path(invoice), class: "btnn btn-square btn-blue btn-small btn-card" %>
                      </div>
                  </div>

                <% end %>
              <% end %>
            </div>

            <div data-toggle-target="togglableElement"  class="row-container d-none">
              <div class="row-width">
                <div class="row row-header sticky-row">
                    <div class="col-3">
                      <p><strong>Nom de l'entreprise :</strong> </p>
                    </div>
                    <div class="col-8 d-flex justify-content-between text-end">
                      <p><strong>Numéro de facture :</strong> </p>
                      <p><strong>Montant de l'encours :</strong></p>
                      <p><strong>Date d'émission:</strong></p>
                      <p><strong>Date de l'échéance :</strong></p>
                    </div>
                  </div>
                  <div class="col-1">
                  </div>
                <div class="row">
                  <% @invoices.each do |invoice|%>
                    <% if invoice.progress != "Payé" %>
                        <div class="d-flex justify-content-between row-content text-aligns-center"
                          data-progress-search-target="card"
                          data-status="<%= invoice.progress.parameterize %>">
                        <div class="top-card col-3">
                          <p class="text-blue-light"><strong><%= invoice.debtor.company_name %> </strong> </p>
                        </div>
                        <div class="middle-row col-8 d-flex justify-content-between text-end ">
                          <div class="w-100">
                              <p><%= invoice.number %> </p>
                          </div>
                          <div class="w-100">
                              <p><%= number_with_precision(invoice.amount, precision: 2, separator: ',', delimiter: ' ') %> €</p>
                          </div>
                          <div class="w-100">
                              <p><%= invoice.emission_date.strftime("%d/%m/%y") %></p>
                          </div>
                          <div class="w-100">
                              <p><%= invoice.due_date.strftime("%d/%m/%y") %></p>
                          </div>
                        </div>
                        <div class="col-1 bottom">
                            <%= link_to  invoice_path(invoice), data:{:title => "Voir plus"}, class: "custom-tooltip-row position-relative"   do %>
                              <i class="fa-solid fa-magnifying-glass fa-lg" style="color: #071425;"></i>
                            <% end %>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
              </div>
          </div>
    </div>
  </div>
</div>

<h2>Hello</h2>

app/views/invoices/new.html.erb
<div class="container my-4">
  <div class="row justify-content-center">
    <div class="forms col-md-6">
      <%= simple_form_for [@invoice], html: { class: 'custom-form' } do |f| %>
        <h1 class="text-center mb-4 ">Dépose une facture</h1>

        <%= f.input :siren, label: 'SIREN du client', input_html: { value: '' } %>
        <%= f.input :number, label: 'Numéro de la facture' %>
        <%= f.input :amount, label: 'Montant de la facture'%>
        <%= f.input :emission_date,
                    as: :string,
                    label: "Date d'émission de la facture",
                    input_html: { data: { controller: "datepicker" } }%>
        <%= f.input :due_date,
                    as: :string,
                    label: "Date d'échéance de la facture",
                    input_html: { data: { controller: "datepicker" } }%>
        <%= f.input :comment, label: "Commentaires" %>
        <%= f.input :file, as: :file %>
        <div class="d-flex justify-content-center">
        <%= f.submit "Dépose ta facture", class: "btnn btn-square btn-medium  btn-purple my-3 " %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/invoices/show.html.erb
<div class="container" style="
    height: 100%;"  data-controller="toggle">
  <div class="row" style="
    height: 100%;" >
      <div class="col-6 d-flex align-items-center justify-content-center">
          <div class="card-show card-bg-white" >
              <div class="display-info">
                <h3 class="my-3 text-blue-light align-items-center"><strong> <%= @invoice.debtor.company_name %> </strong></h3>
                <p class="num-invoice-show pb-3"><strong>Numéro de facture : </strong><%= @invoice.number %> </strong></p>
              </div>

              <div class="middle-card">
              <div class="date py-4">
                <div class="d-flex justify-content-center text-center align-items-center w-100">
                    <p class="size-text"><strong>Date d'émission</strong> <br><%= @invoice.emission_date.strftime("%d/%m/%y") %></p>
                </div>
                <div class="d-flex justify-content-center text-center align-items-center w-100">
                    <p class="size-text"><strong>Date d'échéance</strong> <br><%= @invoice.due_date.strftime("%d/%m/%y") %></p>
                </div>
              </div>
                <p class="encour-size-show text-center"><i class="fa-solid fa-coins fa-lg" style="color: #FFFFF;"></i>  <%= number_with_precision(@invoice.amount, precision: 2, separator: ',', delimiter: ' ') %> €</p>
              </div>
              <div class="bottom-cards-show ">
                <% if @invoice.file.attached? %>
                <div class="show-img">
                  <%= cl_image_tag(@invoice.file.key, :format => :png) %>
                </div>
                <% end %>
                <div class="button-container">
                  <button data-action="" class="btnn btn-square btn-medium btn-purple " type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample" >Édite ta facture </button>
                  <%= link_to "Liste des factures", invoices_path, class: "btnn btn-square btn-medium btn-blue" %>
                </div>
              </div>
          </div>
       </div>


  <div class="mt-6 col-6 d-flex align-items-center" style="width=100%">
    <% if @invoice.reminders.exists? %>
      <div class="reminders" style="
    width: 100%;">
        <h3 class="my-3">Relances :</h3>
        <div class="title-reminders d-flex justify-content-between">

            <div class=""><strong>Type de relance :</strong></div>
            <div class=" text-center"><strong>Date de la relance :</strong></div>
            <div class=" text-end"><strong>État de la relance :</strong></div>

        </div>
        <% @invoice.reminders.each do |reminder| %>
          <div class="info-reminders d-flex justify-content-between">
            <div class="col-4 text-start">
              <p><%= reminder.reminder_type %></p>
            </div>
            <div class="col-4 text-center">
              <p><%= reminder.action_date.strftime("%d/%m/%y") %></p>
            </div>
            <div class="col-4 text-end">
              <p><%= reminder.progress %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% else %>
  <div class="mt-5 col-6">
    <h5>Cette facture n'a pas encore été traitée</h5>
  </div>
    <% end %>
  </div>
  </div>

  <div class="offcanvas offcanvas-end canva-blue" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>

    <div class="offcanvas-body">
      <div class="d-flex justify-content-center " >
            <div data-toggle-target="togglableElement" class="">
              <%= render 'form_edit', user: @user, invoice: @invoice %>
            </div>
      </div>
    </div>
  </div>