config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :users, only: %i[show]
  resources :invoices, only: %i[index show new create edit update] do
    collection do
      get :archives
    end
  end

  post "incoming_invoice", to: "invoices#incoming_invoice"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="sidebar sticky">
  <div class="container-sidebar">
    <% if user_signed_in? %>
      <div class="top">
        <%= link_to "/", class: "navbar-brand" do %>
          <%= image_tag "logo_survivai.png" %>
        <% end %>
        <%= link_to user_path(current_user), data:{:title => "Tableau de bord"}, class: "custom-tooltip position-relative"   do %>
          <i class="fa-solid fa-house fa-2xl" ></i>
        <% end %>
        <%= link_to  invoices_path,  data:{:title => "Mes factures"}, class: "custom-tooltip position-relative"   do %>
          <i class="fa-solid fa-file fa-2xl"></i>
        <% end %>
        <%= link_to new_invoice_path, data: { title: "Ajouter une facture", bs_toggle:"offcanvas", bs_target: "#offcanvasnew" }, class: "custom-tooltip position-relative", aria: {controls: "offcanvasExample"} do %>
          <i class="fa-solid fa-plus fa-2xl"></i>
        <% end %>
        <div class="offcanvas offcanvas-end canva-blue canva-size" tabindex="-1" id="offcanvasnew" aria-labelledby="offcanvasnew">
          <button type="button" class="btn-close ps-3 pt-3" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          <div class="offcanvas-body">
            <div class="my-3 d-flex justify-content-center " >
              <div data-toggle-target="togglableElement" class="size-form">
                <%= render 'invoices/form_new', invoice: Invoice.new %>
              </div>
            </div>
          </div>
        </div>
        <%= link_to  archives_invoices_path,  data:{:title => "Mes archives"}, class: "custom-tooltip position-relative" do %>
          <i class="fa-solid fa-box-archive fa-2xl"></i>
        <% end %>
      </div>
      <div class="bottom">
        <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag "https://d1muf25xaso8hp.cloudfront.net/https%3A%2F%2F28134ce868f2f8a62916a0e24f8ed9de.cdn.bubble.io%2Ff1642684538982x678164592866763900%2FLOGO%2520NOIR%2526BLANC%2520LISERET.png?w=&h=&auto=compress&dpr=1&fit=max", class: "avatar", alt: "dropdown menu" %>
        </a>
        <div class="link-navbar-space">
          <div class="dropdown-navbar" >
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Ajouter une facture", new_invoice_path, class: "dropdown-item" %>
              <%= link_to "Mes factures", invoices_path, class: "dropdown-item" %>
              <%= link_to "Mes archives", archives_invoices_path, class: "dropdown-item" %>
              <%= link_to "Tableau de bord", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
        <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
    <% end %>
  </div>
</div>

app/views/shared/_notification.html.erb
<div class="notification">
  <%= link_to invoices_path do %>
    <div class="notification-content d-flex justify-content-center align-items-center">
      <i class="fa-solid fa-bell fa-xl px-3"></i>
      <div>
        <h3>Vous avez reçu une nouvelle facture</h3>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_ratings.html.erb
<% case rating %>
<% when 5 %>
  <strong> A </strong>
<% when 4 %>
  <strong> B </strong>
<% when 3 %>
  <strong> C </strong>
<% when 2 %>
  <strong> D </strong>
<% when 1 %>
  <strong> E </strong>
<% else %>
  <!-- Gérer le cas où la note n'est pas dans la plage valide -->
  <strong> En cours d'analyse par l'agence</strong>
<% end %>